import { useMemo, useState } from 'react';
import { Check, Pencil, Trash2, X } from 'lucide-react';
import type { WorkDataset } from '../types';

export function GroupEditorView({ dataset, datasets, onChangeGroups, onChange }: { dataset: WorkDataset; datasets: WorkDataset[]; onChangeGroups?: (groups: Record<string, string[]>) => void; onChange: (dataset: WorkDataset) => void }) {
  const [selectedGroup, setSelectedGroup] = useState('');
  const [newGroup, setNewGroup] = useState('');
  const [editingGroup, setEditingGroup] = useState('');
  const [editingName, setEditingName] = useState('');
  const categories = useMemo(() => [...new Set((datasets.length ? datasets : [dataset]).flatMap(item => item.records.map(record => record.originalCategory)))].sort((a, b) => a.localeCompare(b, 'zh-CN')), [datasets, dataset]);
  const groups = dataset.meta.categoryGroups ?? {};
  const categoryOwners = useMemo(() => Object.entries(groups).reduce<Record<string, string>>((owners, [groupName, members]) => { members.forEach(category => { owners[category] = groupName; }); return owners; }, {}), [groups]);
  const updateGroups = (next: Record<string, string[]>) => onChangeGroups ? onChangeGroups(next) : onChange({ ...dataset, meta: { ...dataset.meta, categoryGroups: next } });
  const createGroup = () => { const name = newGroup.trim(); if (!name || groups[name]) return; updateGroups({ ...groups, [name]: [] }); setSelectedGroup(name); setNewGroup(''); };
  const deleteGroup = (name: string) => { if (!window.confirm(`确定删除“${name}”这个自定义大类吗？原始小类和工作记录不会被删除。`)) return; updateGroups(Object.fromEntries(Object.entries(groups).filter(([groupName]) => groupName !== name))); if (selectedGroup === name) setSelectedGroup(''); };
  const startRename = (name: string) => { setEditingGroup(name); setEditingName(name); };
  const cancelRename = () => { setEditingGroup(''); setEditingName(''); };
  const saveRename = (name: string) => { const nextName = editingName.trim(); if (!nextName || (nextName !== name && groups[nextName])) return; const next = Object.fromEntries(Object.entries(groups).map(([groupName, members]) => [groupName === name ? nextName : groupName, members])); updateGroups(next); if (selectedGroup === name) setSelectedGroup(nextName); cancelRename(); };
  const toggleCategory = (category: string) => { if (!selectedGroup) return; updateGroups(Object.fromEntries(Object.entries(groups).map(([name, members]) => [name, name === selectedGroup ? (members.includes(category) ? members.filter(item => item !== category) : [...members, category]) : members.filter(item => item !== category)]))); };
  return <section className="workspace-view"><div className="view-heading"><div><h2>分类大类编辑</h2><p>把多个原始小类归入自定义大类，分类复盘时可按大类统计。原始分类和工作记录不会被修改。</p></div></div><article className="panel category-group-panel"><div className="category-group-head"><div><h3>自定义分类大类</h3><p>一个原始小类同一时间只归入一个大类。灰色小类已归入其他大类，不能重复选择。</p></div><div className="category-group-create"><input value={newGroup} onChange={event => setNewGroup(event.target.value)} placeholder="例如：基层治理"/><button className="primary-small" onClick={createGroup}>新建大类</button></div></div>{Object.keys(groups).length ? <div className="category-group-layout"><div className="category-group-list">{Object.entries(groups).map(([name, members]) => <div key={name} className={`category-group-item${selectedGroup === name ? ' active' : ''}`}>{editingGroup === name ? <div className="category-group-rename"><input autoFocus value={editingName} onChange={event => setEditingName(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') saveRename(name); if (event.key === 'Escape') cancelRename(); }}/><button onClick={() => saveRename(name)} aria-label="保存名称"><Check size={15}/></button><button onClick={cancelRename} aria-label="取消编辑"><X size={15}/></button></div> : <button className="category-group-select" onClick={() => setSelectedGroup(name)}><strong>{name}</strong><span>{members.length} 个小类</span></button>}<button className="category-group-edit" onClick={() => startRename(name)} aria-label={`编辑 ${name}`} title="编辑大类名称"><Pencil size={14}/></button><button className="category-group-delete" onClick={() => deleteGroup(name)} aria-label={`删除 ${name}`} title="删除大类"><Trash2 size={15}/></button></div>)}</div>{selectedGroup && <div className="category-members"><h4>{selectedGroup} · 选择小类</h4><div>{categories.map(category => { const owner = categoryOwners[category]; const locked = Boolean(owner && owner !== selectedGroup); return <label key={category} className={locked ? 'category-locked' : ''} title={locked ? `已归入“${owner}”` : undefined}><input type="checkbox" checked={groups[selectedGroup]?.includes(category) ?? false} disabled={locked} onChange={() => toggleCategory(category)}/><span>{category}</span>{locked && <small>已在“{owner}”</small>}</label>; })}</div></div>}</div> : <div className="category-group-empty">还没有自定义大类。创建后可勾选多个原始小类归入其中。</div>}</article></section>;
}
