import { Cloud, Copy, Database, Download, FileText, LogIn, RefreshCw, Search, Upload } from 'lucide-react';
import { useEffect, useState } from 'react';
import { getPersonalWpsStatus, loginPersonalWps, searchPersonalWpsFiles, type PersonalWpsFile } from '../lib/api';
import type { WorkDataset } from '../types';

const FILE_CONFIG_KEY = 'work-review-personal-wps-file';

export function SettingsView({ dataset, onImport, onClear, onExportConfig, onImportConfig, onConfigureWps, onPersonalImport, onExportAiText, onCopyAiText }: { dataset: WorkDataset; onImport: () => void; onClear: () => void; onExportConfig: () => void; onImportConfig: (file: File) => void; onConfigureWps: () => void; onPersonalImport: (file: PersonalWpsFile) => Promise<void>; onExportAiText: () => void; onCopyAiText: () => void }) {
  return <section className="workspace-view"><div className="view-heading"><div><h2>数据与同步</h2><p>从个人 WPS 云文档选择工作记录，也可以随时导入本地 Excel。</p></div></div><div className="settings-grid"><article className="panel setting-card"><FileStatus icon={<Database/>} title="当前数据源" value={dataset.meta.sourceName}/><dl><div><dt>工作表</dt><dd>{dataset.meta.sheetName}</dd></div><div><dt>年份</dt><dd>{dataset.meta.year}</dd></div><div><dt>导入时间</dt><dd>{new Date(dataset.meta.importedAt).toLocaleString('zh-CN')}</dd></div><div><dt>记录数</dt><dd>{dataset.records.length}</dd></div></dl><button className="primary-action" onClick={onImport}>导入本地 Excel</button></article><PersonalWpsPicker onConfigure={onConfigureWps} onImport={onPersonalImport}/><article className="panel setting-card ai-export-card"><FileStatus icon={<FileText/>} title="AI 年度报告素材" value="文字版 · Markdown"/><p className="setting-note">把年度概览、类别、长期工作项目、未串联事项和完整时间线整理成一份适合交给 AI 的文字稿，不包含图片文件本身。</p><div className="config-backup-actions"><button className="primary-action" onClick={onExportAiText}><Download size={15}/>导出文字稿（.md）</button><button className="secondary-action" onClick={onCopyAiText}><Copy size={15}/>复制到剪贴板</button></div></article><article className="panel setting-card config-backup-card"><FileStatus icon={<Download/>} title="个人配置备份" value="可离线迁移"/><p className="setting-note">只保存事项编号、自定义关联、自定义大类和排除词，不包含原始工作记录和图片。</p><div className="config-backup-actions"><button className="secondary-action" onClick={onExportConfig}><Download size={15}/>保存配置到本地</button><label className="secondary-action"><Upload size={15}/>导入本地配置<input type="file" accept="application/json,.json" onChange={event => { const file = event.target.files?.[0]; if (file) onImportConfig(file); event.currentTarget.value = ''; }}/></label></div></article></div><button className="danger-link" onClick={onClear}>清除当前客户端中的工作记录和图片</button></section>;
}

function PersonalWpsPicker({ onConfigure, onImport }: { onConfigure: () => void; onImport: (file: PersonalWpsFile) => Promise<void> }) {
  const [keyword, setKeyword] = useState('');
  const [files, setFiles] = useState<PersonalWpsFile[]>([]);
  const [selected, setSelected] = useState<PersonalWpsFile>(() => { try { return JSON.parse(localStorage.getItem(FILE_CONFIG_KEY) || 'null'); } catch { return undefined; } });
  const [status, setStatus] = useState<{ available: boolean; authenticated: boolean; message?: string }>();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const refreshStatus = async () => { setStatus(await getPersonalWpsStatus()); };
  useEffect(() => { void refreshStatus(); }, []);
  const login = async () => { setBusy(true); setError(''); try { const result = await loginPersonalWps(); setStatus(result); if (!result.authenticated) setError(result.message || '个人 WPS 登录未完成。'); } catch (reason) { setError(reason instanceof Error ? reason.message : '个人 WPS 登录失败。'); } finally { setBusy(false); } };
  const refresh = async () => { setBusy(true); setError(''); try { const current = status || await getPersonalWpsStatus(); setStatus(current); if (!current.authenticated) { setError(current.message || '请先登录个人 WPS。'); return; } setFiles((await searchPersonalWpsFiles(keyword)).files); } catch (reason) { setError(reason instanceof Error ? reason.message : '个人 WPS 文件列表读取失败。'); } finally { setBusy(false); } };
  const choose = (file: PersonalWpsFile) => { localStorage.setItem(FILE_CONFIG_KEY, JSON.stringify(file)); setSelected(file); };
  return <article className="panel setting-card wps-file-picker"><FileStatus icon={<Cloud/>} title="个人 WPS 云文档" value={selected?.name || (status?.authenticated ? '已登录，尚未选择文件' : status?.available === false ? '需要安装组件' : '未连接')}/><p className="setting-note">使用个人 WPS 账号访问自己的云文档，不需要企业 AppID、AppKey 或 CloudBase。登录凭据由官方组件保存在当前电脑中。</p><div className="settings-wps-actions"><button className="secondary-action" onClick={login} disabled={busy}><LogIn size={15}/>登录个人 WPS</button><button className="primary-action" onClick={refresh} disabled={busy}><RefreshCw size={15} className={busy?'spin':''}/>刷新个人文件</button>{selected&&<button className="secondary-action" onClick={() => onImport(selected)} disabled={busy}>导入已选文件</button>}</div><div className="wps-file-search"><Search size={15}/><input value={keyword} onChange={event=>setKeyword(event.target.value)} placeholder="搜索工作记录、日志或文件名"/><button className="secondary-action" onClick={refresh} disabled={busy}>搜索</button></div>{error&&<div className="dialog-error" role="alert">{error}</div>}{status?.available === false&&<button className="first-run-file-link" onClick={() => window.workReviewDesktop?.openExternal?.('https://github.com/kdocs-app/kdocs-skill')}>安装官方个人 WPS 组件</button>}{files.length>0&&<div className="wps-file-list">{files.map(file=><button className={`wps-file-item${selected?.id===file.id?' active':''}`} key={file.id} onClick={()=>choose(file)}><span><strong>{file.name}</strong><small>{file.modifiedAt?new Date(file.modifiedAt).toLocaleString('zh-CN'):'修改时间未知'}{file.size?` · ${(file.size/1024).toFixed(0)} KB`:''}</small></span><b>{selected?.id===file.id?'已选择':'选择'}</b></button>)}</div>}<button className="first-run-file-link" onClick={onConfigure}>查看个人 WPS 连接说明</button></article>;
}

function FileStatus({icon,title,value}:{icon:React.ReactNode;title:string;value:string}) { return <div className="file-status"><span>{icon}</span><div><small>{title}</small><strong>{value}</strong></div></div>; }
